version: '3.8'

services:
  ascii_web:
    container_name: ascii_web
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    build: ascii_curl
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ascii_web_s.rule=Host(`ascii.peanut.tf`)"
      - "traefik.http.routers.ascii_web_s.entrypoints=websecure"
      - "traefik.http.routers.ascii_web_s.tls=true"
      - "traefik.http.routers.ascii_web_s.tls.certresolver=myresolver"
      - "traefik.http.routers.ascii_web_s.service=ascii_web_s"
      - "traefik.http.services.ascii_web_s.loadbalancer.server.port=$PORT"
      - "traefik.http.routers.ascii_web.rule=Host(`ascii.peanut.tf`)"
      - "traefik.http.routers.ascii_web.entrypoints=web"
      - "traefik.http.routers.ascii_web.service=ascii_web"
      - "traefik.http.services.ascii_web.loadbalancer.server.port=$PORT"
      - "traefik.docker.network=traefik"
    networks:
      - traefik
    volumes:
      - ./ascii_curl/ansi_frames:/ansi_frames/

networks:
  traefik:
    external: true

volumes:
  ansi_frames:
